- platform: template
  sensors:
    stromer_battery:
      friendly_name: "Batterij %"
      device_class: battery
      unit_of_measurement: "%"
      value_template: "{{ states('sensor.stromer_battery_chargelevel') }}"

    stromer_current_speed:
      friendly_name: Snelheid
      unit_of_measurement: km/h
      value_template: "{{ states('sensor.stromer_current_speed') }}"
      icon_template: mdi:bike-fast

    stromer_avg_speed:
      friendly_name: Gemiddelde snelheid
      unit_of_measurement: km/h
      value_template: "{{ states('sensor.stromer_avg_speed') }}"
      icon_template: mdi:speedometer

    stromer_energy_consumption_total:
      friendly_name: Energieverbruik
      device_class: power
      unit_of_measurement: "kw"
      value_template: "{{(states('sensor.stromer_totalenergyconsumption')| float / 1000) | round(2)}}"
      icon_template: mdi:battery

    stromer_km_total:
      friendly_name: Totaal aantal kilometer
      icon_template: mdi:speedometer
      value_template: "{{ states('sensor.stromer_total_distance') }}"
      unit_of_measurement: "km"

    stromer_sw_version:
      friendly_name: Stromer softwareversie
      value_template: "{{ states('sensor.stromer_softwareversion') }}"
      icon_template: mdi:wrench

    stromer_lock_state:
      friendly_name: Slot
      value_template: "{{ states('sensor.stromer_lockstate') }}"
      icon_template: >
        {% if is_state('sensor.stromer_lockstate', 'False') %}
          mdi:lock-open
        {% elif is_state('sensor.stromer_lockstate', 'True') %}
          mdi:lock
        {% else %}
          mdi:lock-alert
        {% endif %}

    stromer_battery_temperatuur:
      friendly_name: Batterijtemperatuur
      unit_of_measurement: "°C"
      value_template: "{{ states('sensor.stromer_batterytemp') }}"
      icon_template: mdi:thermometer

    stromer_battery_health:
      friendly_name: Batterijgezondheid
      device_class: battery
      unit_of_measurement: "%"
      value_template: "{{ states('sensor.stromer_battery_healthstate') }}"

    stromer_motor_temp:
      friendly_name: Motortemperatuur
      unit_of_measurement: "°C"
      value_template: "{{ states('sensor.stromer_motortemp') }}"
      icon_template: mdi:thermometer

    stromer_trip_tijd:
      friendly_name: Triptijd
      unit_of_measurement: "h"
      value_template: "{{(states('sensor.stromer_triptime')| float / 60) | round(2)}}"
      icon_template: mdi:clock

    stromer_totaal_tijd:
      friendly_name: Reistijd
      unit_of_measurement: "h"
      value_template: "{{(states('sensor.stromer_totaltime')| float / 60) | round(2) }}"
      icon_template: mdi:clock
- platform: systemmonitor
  resources:
    - type: disk_use
      arg: /home
    - type: disk_free
      arg: /home
    - type: memory_use
    - type: memory_free
    - type: processor_use
    - type: last_boot
