- platform: template
  switches:
    # TV - Theater
    apple_tv:
      friendly_name: AppleTV
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Apple TV kijken') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "Apple TV kijken"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
          activity: "PowerOff"
    switch:
      friendly_name: Nintendo Switch
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Switch spelen') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "Switch spelen"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
          activity: "PowerOff"
    xbox:
      friendly_name: Xbox
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Xbox spelen') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "Xbox spelen"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
          activity: "PowerOff"
    android:
      friendly_name: Android
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Android kijken') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "Android kijken"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
          activity: "PowerOff"
